console.log('i splashtext.js');
const splashtext = document.getElementById('splashtext');

const splashes = ['You spend your whole life inside your head, make it a nice place to be.',
    'It\'s not the stab in the back that kills you... It\'s when you turn around and see who\'s holding the knife',
    'Everyone can make you smile, but only certain people can make you happy',
    'The only person I lost, and needed back... Was myself',
    'You can never make the same mistake twice... Because the second time it\'s not a mistake',
    'Love what you got. Until life teaches you to love what you\'ve lost',
    'It all comes down to the last person you think of at night. That is the person you love',
    'Difference between school and life. In school. You\'re taught a lesson.. and the given a test. In life. Your given a test, and then you\'re taught a lesson',
    'Only those who truly care about you... Can hear you when your quiet.',
    'Don\'t wait. Times will never be just right.',
    'Life is not a problem to be solved, but a reality to be experienced.',
    'Always remember that you are absolutely unique. Just like everyone else.',
    'Don\'t judge each day by the harvest you reap but by the seeds that you plant.',
    'Start where you are. Use what you have. Do what you can.',
    'If my life is going to mean anything, I have to live it myself.',
    'You know you\'re in love when you can\'t fall asleep because reality is finally better than your dreams.',
    'Tell me and I forget. Teach me and I remember. Involve me and I learn.',
    'The future belongs to those who believe in the beauty of their dreams.',
    'Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.',
    'It does not matter how slowly you go, so long as you do not stop.',
    'Try not to become a person of success, but rather try to become a person of value.',
    'If I had eight hours to chop down a tree, I\'d spend six hours sharpening my axe.',
    'Don\'t wait for your feelings to change to take action. Take action and your feelings will change.',
    'If you continue to think the way you\'ve always thought, you\'ll continue to get what you\'ve always got.',
    'The foolish man seeks happiness in the distance, the wise grows it under his feet.',
    'Do not go where the path may lead, go instead where there is no path and leave a trail.',
    'To accomplish great things, we must not only act, but also dream, not only plan, but also believe.',
    'It is a sad fate for a man to die too well known to everybody else, and still unknown to himself.',
    'Whoever is happy will make others happy too.',
    'When the going gets tough, the tough get going.',
    'Motivation is what gets you started. Habit is what keeps you going.',
    'The best way to predict the future is to create it.',
    'Not how long, but how well you have lived is the main thing.',
    'We are what we repeatedly do. Excellence, then, is not an act, but a habit.',
    'Opportunities don\'t happen, you create them.',
    'It is during our darkest moments that we must focus to see the light.',
    'Never to suffer would never to have been blessed.',
    'Action may not always bring happiness, but there is no happiness without action.',
    'As we look ahead into the next century, leaders will be those who empower others.',
    'Success comes from having dreams that are bigger than your fears.',
    'You can never cross the ocean until you have the courage to lose sight of the shore.',
    'Sometimes you win, sometimes you learn.',
    'Challenges are what make life interesting. Overcoming them is what makes life meaningful.',
    'Never do tomorrow what you can do today. Procrastination is the thief of time.',
    'Don\'t spend time beating on a wall, hoping to transform it into a door.',
    'We become what we think about most of the time, and that\'s the strangest secret.',
    'Perfection is boring. Getting better is where all the fun is.',
    'It\'s hard to beat a person who never gives up.',
    'Build your own dreams, or someone else will hire you to build theirs.',
    'Never give up, for that is just the place and time that the tide will turn.',
    'Life is not about finding yourself. Life is about creating yourself.',
    'If you are not willing to risk the usual you will have to settle for the ordinary.',
    'It\'s not what you look at that matters, it\'s what you see.',
    'It is better to fail in originality than to succeed in imitation.',
    'The harder the battle, the sweeter the victory.',
    'Don\'t be afraid to give up the good to go for the great.',
    'The only person you should try to be better than, is the person you were yesterday.',
    'Life shrinks or expands in proportion to one\'s courage.',
    'Life is too deep for words, so don\'t try to describe it, just live it.',
    'Could I have been anyone other than me?',
    'I want to be like water. I want to slip through fingers, but hold up a ship.',
    'One way to keep momentum going is to have constantly greater goals.',
    'There are two ways of spreading light. To be the candle, or the mirror that reflects it.',
    'You may have to fight a battle more than once to win it.',
    'All progress takes place outside the comfort zone.',
    'There is a wisdom of the head, and… there is a wisdom of the heart.',
    'The world breaks everyone, and afterward, some are strong at the broken places.',
    'He who opens a school door, closes a prison.',
    'There is no truth. There is only perception.',
    'Every strength is also a weakness. The opposite is true as well.',
    'Common sense is in spite of, not the result of, education.',
    'All the mistakes I ever made in my life were when I wanted to say No, and said Yes.',
    'The more you know who you are, and what you want, the less you let things upset you.',
    'If you want to overcome the whole world, overcome yourself.',
    'The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.',
    'Every man is born as many men and dies as a single one.',
    'You can\'t depend on your eyes when your imagination is out of focus.'
];

const index = Math.floor(Math.random() * splashes.length);
console.log('randomized', 'Splashtext="', splashes[index], '"');

splashtext.innerHTML = splashes[index]
